//==================================================
//     Outputs that match the input variables
//==================================================
output "domain_to" {
  description = "The value of the `domain_to` input variable."
  value       = var.domain_to
}
output "redirect_type" {
  description = "The value of the `redirect_type` input variable, or the default value if the input was `null`."
  value       = var.redirect_type
}
output "redirect_static_path" {
  description = "The value of the `redirect_static_path` input variable, or the default value if the input was `null`."
  value       = var.redirect_static_path
}
output "redirect_path_prefix" {
  description = "The value of the `redirect_path_prefix` input variable, or the default value if the input was `null`."
  value       = var.redirect_path_prefix
}
output "redirect_code" {
  description = "The value of the `redirect_code` input variable, or the default value if the input was `null`."
  value       = var.redirect_code
}


//==================================================
//       Outputs generated by this module
//==================================================
output "cloudfront_function" {
  description = "The `aws_cloudfront_function` resource that was created."
  value       = aws_cloudfront_function.redirect
}
